# Generated by Django 5.2.6 on 2025-10-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
