# Generated by Django 5.2.6 on 2025-10-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_products_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="data_size",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
